### PR TITLE
#19 refactoring

### PR DESCRIPTION
**Pull request by jwanner83**
Requirements which need to be satisfied before merge.
- [x] Rollup bundle process has moved away from the `liferay-npm-bundler-improved`
- [x] Localization feature works
- [x] Logging has been refactored and doesn't use as much space as before

~~Configuration feature works~~
~~Assets feature works~~

### CODE REVIEW

**Comment by jwanner83** [comment]
https://github.com/jwanner83/liferay-npm-bundler-improved/blob/%2319-refactoring/src/handler/PackageHandler.ts#L9 please use `path` instead of `./` or something like this because of (🤮) win**dos**

**Comment by jwanner83** [comment]
The configuration and assets features will not be done in this pull request.

**Comment by jwanner83** [comment]
Localization feature works! Lets get logging to a good state and merge!

**Comment by moisout** [comment]
Good luck!

**Comment by jwanner83** [comment]
LGTM!

**Pull request merged**
